services:
  gym-tracking-db:
    image: postgres
    container_name: gym-tracking-db-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - gym-tracking-network
    volumes:
      - gym-tracking-db-data:/var/opt/postgresql/data
  nutrition-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nutrition-db-mssql
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    ports:
      - "1433:1433"
    networks:
      - nutrition-network
    volumes:
      - nutrition-db-data:/var/lib/mssql/data
  redis:
    image: redis:latest
    container_name: redis-cache-container
    ports:
      - "6379:6379"
    networks:
      - gym-tracking-network
      - nutrition-network
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq-message-broker
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gym-tracking-network
      - nutrition-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: GymApp.Ocelot.Gateway/Dockerfile
  #   container_name: api-gateway
  #   ports:
  #     - "5000:8080"
  #   networks:
  #     - gym-tracking-network
  #     - nutrition-network
  #   depends_on:
  #     - gym-tracking-db
  #     - nutrition-db
  #     - redis
  #     - rabbitmq
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080

networks:
  nutrition-network:
    driver: bridge
  gym-tracking-network:
    driver: bridge

volumes:
  gym-tracking-db-data:
  nutrition-db-data:
  rabbitmq-data:
  redis-data: